### ISSUE TITLE
Extending a pregnant model with fetal subcompartments

### ISSUE THREAD

**Issue by EAalgh** [Open-Systems-Pharmacology/Pregnancy-Models#19]
Hi there, I followed the tutorial of Dallman et al to add new compartments  (here is fetal brain ) to an existing pregnant model in MoBi. I managed ti intorduce Fetal Brain and make all wiring to circulation. At the step of defining the partition coefficient  Interstital/Water (step #5 in the suppl. information tutorial), I can find "PARAM_K_Water_INT_FetalBrain" on the drop-down menu option, only "PARAM_K_Water_INT_Fetus". 
I wonder if something is missing in the Spatial structure that I made.
Compartemnt FetalBrain is connected to neiborhood ArterialBlood_UmbilicalCord and VenousBlood_Umbilical Cord. 
The MoBi file is attached.
Thanks in advance!
[Pregnant_fetal Brain_extension_2.zip](https://github.com/Open-Systems-Pharmacology/Pregnancy-Models/files/6816421/Pregnant_fetal.Brain_extension_2.zip)

**Comment by AndreDlm** [comment]
Hi @EAalgh, thanks for sharing your model. Looking at your model, I can confirm that you have a `Partition coefficient  (interstitial/water)` implemented in the neighborhood of `FetalBrain_int_FetalBrain_Cell`. However, the *potential* issue is that this `Partition coefficient  (interstitial/water)` uses the formula that has been defined for the `Fetus` compartment, i.e. the value of the partition coefficient in the `Brain` compartment will always be the same as in the `Fetus` compartment.

Note, that the `Partition coefficient  (interstitial/water)` is calculated from fraction unbound (fu) and the Partition coefficient (interstitial/**plasma**) as follows:
![image](https://user-images.githubusercontent.com/26541603/127295901-4f2c4abb-139f-476f-88b0-fcf284f79555.png)

And the Partition coefficient (interstitial/**plasma**) is calculated as follows:
![image](https://user-images.githubusercontent.com/26541603/127295780-13ef660f-5f8e-44ea-b87a-06d0aafe9f0e.png)

Hence, if you assume that all variables in this equation have the same value in the `Fetus` compartment and the `FetalBrain` compartment, then you don't need to change anything. You can find more information on the equation above [here](https://www.sciencedirect.com/science/article/pii/S0887233307002573).

If you want different drug partitioning between interstitial and water compartments in the `FetalBrain` and `Fetus`, then you need to define a new equation for the `Partition coefficient (interstitial/water)` in the neighborhood of the `FetalBrain` as described in step 5) of the tutorial.

I hope this helps!

André

**Comment by EAalgh** [comment]
Hello again, 
Thanks for the help. I now have a pregnant model extended to inlcude 2 fetal subcompartments. The last step should be to create a simulation using the new spatial sturcture and then export it to pKsim. When I try to create a simulation I get an error message.
![image](https://user-images.githubusercontent.com/84385506/135580301-d1e78e71-59c9-4c34-8547-a79f51bcbdd7.png)
If I save the already existing simulation that I have in MoBi before extending to the fetal subcompartment as pkml file and try to import it to pksim, I get another error message.
![image](https://user-images.githubusercontent.com/84385506/135580541-db9d6757-9b52-4c26-bb36-36e764cfa959.png)
What I did is that i extended my model which was created in pregnant woman (attached pkml: trialpregsim) to inlcude fetal sub compartments in Mobi (Pregnant fetal brain extension k values).

I attach the respective files for reference.

[pregnant fetal_Brain extension_3.zip](https://github.com/Open-Systems-Pharmacology/Pregnancy-Models/files/7265075/pregnant.fetal_Brain.extension_3.zip)

Thanks in advance!

**Comment by EAalgh** [comment]
Hello again,
Thanks for the help. I now have a pregnant model extended to inlcude 2 fetal subcompartments. The last step should be to create a simulation using the new spatial sturcture and then export it to pKsim. When I try to create a simulation I get an error message.
https://user-images.githubusercontent.com/84385506/135580301-d1e78e71-59c9-4c34-8547-a79f51bcbdd7.png
If I save the already existing simulation that I have in MoBi before extending to the fetal subcompartment as pkml file and try to import it to pksim, I get another error message.
https://user-images.githubusercontent.com/84385506/135580541-db9d6757-9b52-4c26-bb36-36e764cfa959.png
What I did is that i extended my model which was created in pregnant woman (attached pkml: trialpregsim) to inlcude fetal sub compartments in Mobi (Pregnant fetal brain extension k values).

I attach the respective files for reference. 

pregnant fetal_Brain extension_3.zip

Thanks in advance!

**Comment by AndreDlm** [comment]
Hello @EAalgh, has this issue been solved in the meantime or do you still need help?

**Comment by AndreDlm** [comment]
Dear @EAalgh, I will close this issue. Please re-open if the issue still persists. Thanks
