### ISSUE TITLE
Fetal or maternal hematocrit value in fetal passive transports

### ISSUE THREAD

**Issue by SoFiHo05** [Open-Systems-Pharmacology/Pregnancy-Models#27]
Hi, 
I am working on a pregnancy model, building up on your work. In doing so, I encountered the following question: 
In the BB PassiveTransport_Pregnancy.pkml, the maternal hematocrit value is used for transports on the fetal side of the placenta and the fetus itself. 
@AndreDlm and @Yuri05 should that be updated with the fetal hematocrit value? 

![image](https://github.com/user-attachments/assets/627e8f77-2cd1-462b-bbf7-09a67d939a7e)

Thanks! 
Sophie

**Comment by AndreDlm** [comment]
Yes that should be corrected
