### ISSUE TITLE
new MoBi model for pregnancy

### ISSUE THREAD

**Issue by zt1947** [Open-Systems-Pharmacology/Pregnancy-Models#3]
Is the tutorial for setting up new MoBi pregnancy models available?
Can I convert an existing MoBi pregnancy file, to address another drug (i.e. not the drug for which the original model was setup)

**Comment by Yuri05** [comment]
>Can I convert an existing MoBi pregnancy file, to address another drug (i.e. not the drug for which the original model was setup)

Yes, it's possible. The tutorial will be published soon. Stay tuned

**Comment by zt1947** [comment]
Thanks!

**Comment by Yuri05** [comment]
The tutorial for creating new pregnancy models in MoBi is now available and can be found [here](https://doi.org/10.1002/psp4.12300).

**Comment by AndreDallmann** [comment]
Dear Zvi,

thank you for your interest in our articles.
I am first author of the mentioned articles and have send you a link to a view-only version via mail.

Best,
André
